// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Hardcoded fallback values for when env vars aren't loaded
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://oukxkpihsyikamzldiek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91a3hrcGloc3lpa2FtemxkaWVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUzODU4NTYsImV4cCI6MjA4MDk2MTg1Nn0.Lv5cGSFojHWLaQRius26N1HvbK7OnswrieS3mhfjOD0";

// Check if we're in offline mode (env vars not found, using fallbacks)
export const isOfflineMode = !import.meta.env.VITE_SUPABASE_URL || !import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});